# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x0breplication\"k\n\x08LogEntry\x12\r\n\x05index\x18\x01 \x01(\x04\x12\x0c\n\x04term\x18\x02 \x01(\x04\x12\x0e\n\x06opcode\x18\x03 \x01(\t\x12\x10\n\x03key\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x03val\x18\x05 \x01(\tH\x01\x88\x01\x01\x42\x06\n\x04_keyB\x06\n\x04_val\"\xa5\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x04\x12\x15\n\rprev_log_term\x18\x04 \x01(\x04\x12&\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x15.replication.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x04\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0f\n\x07success\x18\x02 \x01(\x08\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x04\x12\x15\n\rlast_log_Term\x18\x04 \x01(\x04\"9\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGENTRY']._serialized_start=27
  _globals['_LOGENTRY']._serialized_end=134
  _globals['_APPENDENTRIESREQUEST']._serialized_start=137
  _globals['_APPENDENTRIESREQUEST']._serialized_end=302
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=304
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=358
  _globals['_REQUESTVOTEREQUEST']._serialized_start=360
  _globals['_REQUESTVOTEREQUEST']._serialized_end=463
  _globals['_REQUESTVOTERESPONSE']._serialized_start=465
  _globals['_REQUESTVOTERESPONSE']._serialized_end=522
# @@protoc_insertion_point(module_scope)
